spring:
    application:
        name: spring-event-bus-client

    config:
        import: configserver:http://localhost:8080

    rabbitmq:
        host: localhost
        port: 5672
        username: user
        password: password

server:
    port: 8081

management:
    endpoints:
        web:
            exposure:
                include: "*"